### ISSUE TITLE
viz example gallery

### ISSUE THREAD

**Issue by context-dependent** [context-dependent/bp-big-book#9]
The viz section needs examples. First, we need some non-sensitive but representative data. For this, we await simulated data from alex-rand/fsc-benchmarks. Alternatively, I could build out the surveysim package, though it's hard and I'm lazy.

**Comment by alex-rand** [comment]
[faux package](https://debruine.github.io/faux/) also perhaps of interest

**Comment by context-dependent** [comment]
oh that actually seems perfect. Might be messy or manual to illustrate skip logic, but that's probably chill.

**Comment by context-dependent** [comment]
@alex-rand I'm trying to pick a program from which to generate simulated data. Do you have an opinion on which would be best? I'm looking for something with an archetypal survey structure (baseline, exit, follow-up), clean linkages, and decent response rates.

**Comment by alex-rand** [comment]
ADaPT and CCDF seem to have good SF linkage rates, and they both have multiple timepoints. I'd probably start with one of those

**Comment by context-dependent** [comment]
Thanks! I think ADaPT is the one. CCDF has a bit too much going on.
